# This file has been moved to .config/docker/docker-compose.yml
# This is a compatibility wrapper

version: '3'

services:
  etorotrade:
    extends:
      file: .config/docker/docker-compose.yml
      service: etorotrade
  
  tests:
    extends:
      file: .config/docker/docker-compose.yml
      service: tests