version: '3'

services:
  etorotrade:
    build:
      context: ../..
      dockerfile: .config/docker/Dockerfile
    volumes:
      - ../../yahoofinance/input:/app/yahoofinance/input
      - ../../yahoofinance/output:/app/yahoofinance/output
      - ../../logs:/app/logs
    environment:
      - ETOROTRADE_LOG_LEVEL=INFO
      - PYTHONPATH=/app
    ports:
      - "8000:8000"  # For potential web dashboard in the future
    command: python trade.py
  
  tests:
    build:
      context: ../..
      dockerfile: .config/docker/Dockerfile
    volumes:
      - ../../tests:/app/tests:ro  # Read-only mount for tests
      - ../../yahoofinance:/app/yahoofinance:ro  # Read-only mount for source code
      - ../../requirements.txt:/app/requirements.txt:ro
      - ../../pyproject.toml:/app/pyproject.toml:ro
      - ../../setup.py:/app/setup.py:ro
      - ../../run_tests.sh:/app/run_tests.sh:ro
    command: ./run_tests.sh --all