"""Tests for scripts/dev/adopt_export_pins.py.

The script pulls Dependabot's export-only pins back into poetry.lock by
dropping the affected `[[package]]` blocks and re-running `poetry lock`.

Regression context (2026-08-17, PR #227): poetry.lock keeps its top-level
`[extras]` and `[metadata]` tables AFTER the final `[[package]]` block, so a
split on `[[package]]` boundaries folds them into that last package's segment.
When the alphabetically-last package was one of the ones being dropped
(yfinance 1.5.2 -> 1.6.0 in the production-dependencies group), `[metadata]`
went with it and `poetry lock` aborted with "The lock file does not have a
metadata entry", which took down the Dependabot Auto-Relock job and, with it,
the `lockfile sync` and `test` jobs on the PR.
"""

import importlib.util
from pathlib import Path

import pytest

SCRIPT_PATH = (
    Path(__file__).parent.parent.parent.parent / "scripts" / "dev" / "adopt_export_pins.py"
)

LOCK_TEXT = """\
# This file is automatically @generated by Poetry 2.4.0 and should not be changed by hand.

[[package]]
name = "alpha"
version = "1.0.0"
description = "first"
optional = false
python-versions = ">=3.10"
files = []

[[package]]
name = "middle"
version = "2.0.0"
description = "second"
optional = false
python-versions = ">=3.10"
files = []

[package.dependencies]
alpha = ">=1.0.0"

[[package]]
name = "yfinance"
version = "1.5.2"
description = "last one alphabetically"
optional = false
python-versions = ">=3.10"
files = []

[package.extras]
repair = ["scipy (>=1.6.3)"]

[extras]
dev = ["pytest"]

[metadata]
lock-version = "2.1"
python-versions = ">=3.10,<4.0"
content-hash = "0000000000000000000000000000000000000000000000000000000000000000"
"""


@pytest.fixture(scope="module")
def aep():
    spec = importlib.util.spec_from_file_location("adopt_export_pins", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_locked_versions_reads_every_package(aep):
    assert aep.locked_versions(LOCK_TEXT) == {
        "alpha": "1.0.0",
        "middle": "2.0.0",
        "yfinance": "1.5.2",
    }


def test_dropping_last_package_keeps_extras_and_metadata(aep):
    """The regression: `[extras]`/`[metadata]` trail the final package block."""
    result = aep.drop_blocks(LOCK_TEXT, {"yfinance"})

    assert "[metadata]" in result
    assert "[extras]" in result
    assert 'content-hash = "0000' in result
    assert 'name = "yfinance"' not in result
    assert 'name = "alpha"' in result
    assert 'name = "middle"' in result


def test_dropping_middle_package_keeps_extras_and_metadata(aep):
    result = aep.drop_blocks(LOCK_TEXT, {"middle"})

    assert "[metadata]" in result
    assert "[extras]" in result
    assert 'name = "middle"' not in result
    assert 'name = "alpha"' in result
    assert 'name = "yfinance"' in result


def test_dropping_nothing_is_a_no_op(aep):
    assert aep.drop_blocks(LOCK_TEXT, set()) == LOCK_TEXT
